principal: Fabrica.o Factura.o Mozo.o Mesa.o ManejadorMozo.o ManejadorMesa.o ControladorCargaDatos.o DtAsignacion.o DtFactura.o DtFecha.o DtFechaHora.o DtProducto.o DtProductoBase.o DtProductoCantidad.o DtProductoFactura.o ProductoMenu.o VentaLocal.o VentaProducto.o Comun.o Producto.o ManejadorProducto.o ManejadorVenta.o Menu.o ControladorAgregarProdAVenta.o ControladorBajaProducto.o ControladorQuitarProducto.o ControladorIniciarVenta.o ControladorAltaProducto.o ControladorFacturacion.o ControladorVerInfoProducto.o main.o
	g++ Fabrica.o Factura.o Mozo.o Mesa.o ManejadorMozo.o ManejadorMesa.o ControladorCargaDatos.o DtAsignacion.o DtFactura.o DtFecha.o DtFechaHora.o DtProducto.o DtProductoBase.o DtProductoCantidad.o DtProductoFactura.o ProductoMenu.o VentaLocal.o VentaProducto.o Comun.o Producto.o ManejadorProducto.o ManejadorVenta.o Menu.o ControladorAgregarProdAVenta.o ControladorBajaProducto.o ControladorQuitarProducto.o ControladorIniciarVenta.o ControladorAltaProducto.o ControladorFacturacion.o ControladorVerInfoProducto.o main.o -o programa
	
Fabrica.o: Fabrica.cpp

Factura.o: Factura.cpp

Mozo.o: Mozo.cpp

Mesa.o: Mesa.cpp

ControladorCargaDatos.o: ControladorCargaDatos.cpp

ManejadorMesa.o: ManejadorMesa.cpp

ManejadorMozo.o: ManejadorMozo.cpp

DtAsignacion.o: DtAsignacion.cpp

DtFactura.o: DtFactura.cpp

DtFecha.o: DtFecha.cpp

DtProducto.o: DtProducto.cpp

DtProductoBase.o: DtProductoBase.cpp

DtProductoCantidad.o: DtProductoCantidad.cpp

DtProductoFactura.o: DtProductoFactura.cpp

ProductoMenu.o: ProductoMenu.cpp

VentaLocal.o: VentaLocal.cpp

VentaProducto.o: VentaProducto.cpp

Comun.o: Comun.cpp

Producto.o: Producto.cpp

ManejadorProducto.o: ManejadorProducto.cpp

ManejadorVenta.o: ManejadorVenta.cpp

Menu.o: Menu.cpp

ControladorAgregarProdAVenta.o: ControladorAgregarProdAVenta.cpp

ControladorBajaProducto.o: ControladorBajaProducto.cpp

ControladorQuitarProducto.o: ControladorQuitarProducto.cpp

ControladorIniciarVenta.o: ControladorIniciarVenta.cpp

ControladorAltaProducto.o: ControladorAltaProducto.cpp

ControladorFacturacion.o: ControladorFacturacion.cpp

ControladorVerInfoProducto.o: ControladorVerInfoProducto.cpp

main.o: main.cpp

comp:
	clear
	rm -rf *.o programa
	make
	rm -rf *.o
	./programa
	
